"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { useAuth } from "@/contexts/AuthContext";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { FileOutput, Download, Printer, Calendar, Pill, Activity, ClipboardList } from "lucide-react";
import { cn } from "@/lib/utils";

interface Supplement {
  id: string;
  name: string;
  category: string;
  dose: string;
  timing: string;
  status: string;
  reason: string;
  prescriber?: string;
  refill_date?: string;
}

interface Protocol {
  id: string;
  title: string;
  type: string;
  content: string;
}

export default function ExportReport() {
  const { user } = useAuth();
  const [supplements, setSupplements] = useState<Supplement[]>([]);
  const [protocols, setProtocols] = useState<Protocol[]>([]);
  const [notes, setNotes] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user) fetchData();
  }, [user]);

  const fetchData = async () => {
    setLoading(true);
    const { data: supplementsData } = await supabase.from("supplements").select("*").eq("user_id", user!.id).eq("status", "active").order("timing", { ascending: true });
    const { data: protocolsData } = await supabase.from("protocols").select("*").eq("user_id", user!.id).eq("type", "pt-routine").order("title");
    setSupplements(supplementsData || []);
    setProtocols(protocolsData || []);
    setLoading(false);
  };

  const generateReport = () => {
    const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const lines = [
      "Erinlè Health Protocol Report",
      `Generated: ${today}`,
      "",
      "CURRENT ACTIVE SUPPLEMENTS / PRESCRIPTIONS SCHEDULE",
      "",
      ...supplements.map((s) => `- ${s.name} (${s.category}) - Dose: ${s.dose || "N/A"} - Timing: ${s.timing || "N/A"}${s.reason ? ` - Reason: ${s.reason}` : ""}${s.prescriber ? ` - Prescriber: ${s.prescriber}` : ""}${s.refill_date ? ` - Refill: ${s.refill_date}` : ""}`),
      "",
      "PT ROUTINE",
      "",
      ...protocols.map((p) => `${p.title}\n${p.content}`),
      "",
      "NOTES",
      "",
      notes || "__________________________________________________________",
    ];

    return lines.join("\n");
  };

  const downloadReport = () => {
    const blob = new Blob([generateReport()], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `erinle-health-report-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const printReport = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>Erinlè Health Protocol Report</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #333; }
            h1 { color: #0EA5E9; font-size: 24px; }
            h2 { color: #0EA5E9; font-size: 18px; margin-top: 30px; }
            .section { white-space: pre-wrap; line-height: 1.6; }
            .footer { margin-top: 50px; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <h1>Erinlè Health Protocol Report</h1>
          <div class="section">${generateReport().replace(/</g, "&lt;")}</div>
          <div class="footer">Generated by Erinlè Health Protocol Tracker</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  if (loading) {
    return <div className="flex h-96 items-center justify-center"><div className="h-10 w-10 animate-spin rounded-full border-4 border-primary border-t-transparent" /></div>;
  }

  return (
    <div className="space-y-6 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="font-heading text-3xl font-bold">Export Report</h1>
          <p className="text-sm text-muted-foreground mt-1">Create a summary for your appointments</p>
        </div>
      </div>

      <div className="flex flex-wrap gap-3 no-print">
        <Button onClick={downloadReport} className="bg-primary hover:bg-primary/90">
          <Download className="mr-2 h-4 w-4" /> Download .txt
        </Button>
        <Button onClick={printReport} variant="outline">
          <Printer className="mr-2 h-4 w-4" /> Print Report
        </Button>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="text-lg font-heading flex items-center gap-2">
              <Pill className="h-5 w-5 text-primary" /> Active Supplements / Prescriptions
            </CardTitle>
          </CardHeader>
          <CardContent>
            {supplements.length === 0 ? (
              <p className="text-sm text-muted-foreground">No active items yet.</p>
            ) : (
              <div className="space-y-3">
                {supplements.map((s) => (
                  <div key={s.id} className="rounded-lg border p-3">
                    <div className="flex items-center gap-2">
                      <span className="font-medium">{s.name}</span>
                      <Badge variant={s.category === "prescription" ? "default" : "secondary"}>{s.category}</Badge>
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">{s.dose} • {s.timing}</p>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-lg font-heading flex items-center gap-2">
              <Activity className="h-5 w-5 text-primary" /> PT Routine
            </CardTitle>
          </CardHeader>
          <CardContent>
            {protocols.length === 0 ? (
              <p className="text-sm text-muted-foreground">No PT routines yet.</p>
            ) : (
              <div className="space-y-3">
                {protocols.map((p) => (
                  <div key={p.id} className="rounded-lg border p-3">
                    <h4 className="font-medium">{p.title}</h4>
                    <p className="text-sm text-muted-foreground mt-1 whitespace-pre-wrap">{p.content}</p>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-lg font-heading flex items-center gap-2">
            <ClipboardList className="h-5 w-5 text-primary" /> Notes for Appointment
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Textarea
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Add any notes you want to discuss with your provider..."
            className="min-h-[120px]"
          />
        </CardContent>
      </Card>
    </div>
  );
}
